### ISSUE TITLE
Varnishd 3.0.5 throws configuration errors on environment variables in default.vcl

### ISSUE THREAD

**Issue by CCTJNII** [jacksoncage/varnish-docker#2]
When using the environment variables in the provided default.vcl Varnish does not start with the following error:

```
Message from VCC-compiler:
Backend host '"${VARNISH_BACKEND_IP}"' could not be resolved to an IP address:
        Servname not supported for ai_socktype
(Sorry if that error message is gibberish.)
('input' Line 8 Pos 13)
    .host = "${VARNISH_BACKEND_IP}";
------------#######################-


In backend specification starting at:
('input' Line 7 Pos 1)
backend default {
#######----------

Running VCC-compiler failed, exit 1

VCL compilation failed
Cannot open /var/lib/varnish/1305ff82c212/_.vsm: No such file or directory
```

Running bash in the container I see the variables are set as expected:

```
root@9da34043f814:/# echo "${VARNISH_BACKEND_IP}"
172.28.98.83
root@9da34043f814:/# echo "${VARNISH_BACKEND_PORT}"
6780
```

If I replace ${VARNISH_BACKEND_IP} and ${VARNISH_BACKEND_PORT} witht the IP and port varnishd starts and operates as expected.  Per http://stackoverflow.com/questions/21056450/how-to-inject-environment-variables-in-varnish-configuration it looks like environment variables in the backend config no longer supports environment variables.

Container was built from 2d9aae961cbb3cb6630a372cfd54fac5e4c505df

**Comment by dukebody** [comment]
There are more people having this problem, see http://stackoverflow.com/questions/27875904/docker-varnish-connection-reset-by-peer

**Comment by jacksoncage** [comment]
Thanks and sorry for my late reply @CCTJNII @dukebody. Pull request are now merged and a new version is up on Docker Hub.
