### ISSUE TITLE
file system partition

### ISSUE THREAD

**Issue by edsu** [jacksoncage/varnish-docker#4]
Have you ever noticed your /var/lib/docker/container filling up till it's out of space when running varnish under docker? I guess I only noticed because I'm running varnish on a small ec2 instance that only has an 8G root partition, which doesn't seem to take too long to fill up.

Is it possible that unionfs is recording all the changes that happen to /var/lib/varnish and this is bloating the container? Perhaps a volume should be used so unionfs doesn't track all the changes?

**Comment by jacksoncage** [comment]
Thanks for the issue @edsu and sorry for the late replay. I havn't seen this my self, but that could happen on a smaller instance.

Both `/var/lib/varnish` and `/etc/varnish` should be available via volumes.
